### ISSUE TITLE
Question: How to add livy chart as dependent chart

### ISSUE THREAD

**Issue by manjiler** [jahstreet/spark-on-kubernetes-helm#65]
First off - amazing work get this helm chart!!!

I tried specifying the dependencies 
```
dependencies:
- name: livy
  version: "v2.0.2"
  repository: https://jahstreet.github.io/helm-charts

```

It does not work. 
I might be doing something wrong here. 

What is correct way to add livy chart as a dependencies?

**Comment by manjiler** [comment]
For now I am manually copied helm chart for livy and added it under charts folder. 
Let me if there is better way to do it.

**Comment by jahstreet** [comment]
Hi @manjiler , thx for the feedback. Can you share the errors you observe?

**Comment by manjiler** [comment]
After adding livy as dependency in Chart.yaml. Running helm dependency update, give the below error
`
Error: can't get a valid version for repositories livy. Try changing the version constraint in Chart.yaml
`

Sample Chart.yaml
```
dependencies:
- name: livy
  version: "v2.0.2"
  repository: https://jahstreet.github.io/helm-charts
```
